resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/68648612f916e8adaf6c9ca5fe39bc6712470a6a/snapshot.yaml

packages:
  - .

extra-deps:
    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: b81e722c28ed7d65d93c70b43ea744afd95ea1c3
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: a21f83d9407b2955fbaea4ce8a79b262361112aa
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 501d91e426ae84ce0ae056be38bd3db594af9fc2
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: 52baef406c82b0e1d8858e35ee5597b51b7df48a

  - containers-0.5.11.0
  - ekg-prometheus-adapter-0.1.0.4
  - prometheus-2.1.1
  - pvss-0.2.0
  - time-units-1.0.0
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1
    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: e67ac43fc26e3a47ffcf1a10666f2ccd34ce8b1a
    subdirs:
      - contra-tracer
      - iohk-monitoring

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: e8bfc1294e088f90e5ae0b4aedbc82ee46ac5ee4

  - git: https://github.com/joelwilliamson/bimap
    commit: 013a0639c222b3f5572ae20ce364815e5d8f2156

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: f132a47c7d8711cc2c0457c62509fa1dbcb9347c
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

  # We have to use own fork because of problems with LTS dependencies (QuickCheck 2.12 against 2.13).
  - git: https://github.com/denisshevchenko/ansi-terminal-game
    commit: b0d9aba5684d5fc4681fa12afcf0ac9d4db38747

  - linebreak-1.0.0.3@sha256:3152802008e06f8444d364f6e1047b412e3cb692c1382b1657a425d72a0cfd5f
  - timers-tick-0.4.1.0@sha256:27d345648b8e01fad48adf1dc0e870b19fabb03ccdf3ad0bc5acb57f5da6cb5c

flags:
  iohk-monitoring:
    disable-prometheus: true

nix:
  shell-file: nix/stack-shell.nix
