resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/96e8dcb29dc3c29eee99c0d020152fad6071af6d/snapshot.yaml

packages:
  - cardano-config
  - cardano-node

ghc-options:
  cardano-config:   -Wall -Werror -fwarn-redundant-constraints
  cardano-node:     -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - binary-0.8.7.0
  - bimap-0.4.0
  - containers-0.5.11.0
  - generic-monoid-0.1.0.0
  - pvss-0.2.0
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - transformers-except-0.1.1
  - brick-0.47
  - libsystemd-journal-1.4.4
  - config-ini-0.2.4.0
  - data-clist-0.1.2.2
  - text-zipper-0.10.1
  - word-wrap-0.4.1

    # Cardano-ledger dependencies
  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 5e0322caa11b1a46b70f16addb4b056bccf5696b
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 96e8dcb29dc3c29eee99c0d020152fad6071af6d
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-base
    commit: 80f25cde254d523f34d9804e6e009925d9775adb
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

    # Following deps are for cardano-shell
  - git: https://github.com/input-output-hk/cardano-shell
    commit: a19b6af73a4635169f2e50a2bc3cb29db4154fc3
    subdirs:
      - cardano-shell

    # iohk-monitoring-framework currently not pinned to a release
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 1ebe57df3a76a8ae4e3b5a31a9b85132f71534fc
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd

    # Extracted from cardano-sl since it's quite useful
  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

    #Ouroboros-network dependencies

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: 72feb88457eb8643fabda6095a3e290469b0dc37
    subdirs:
        - io-sim-classes
        - network-mux
        - ouroboros-network
        - ouroboros-consensus
        - typed-protocols
        - typed-protocols-cbor

nix:
  shell-file: nix/stack-shell.nix
