steps:
  - label: 'slow-ci-builds'
    trigger: cardano-node-slow-ci
    async: true
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - label: 'check-cabal-project'
    command: 'nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh'
    agents:
      system: x86_64-linux

# FIXME, waiting for https://github.com/input-output-hk/haskell.nix/pull/426
#  - label: 'release.nix'
#    command: 'nix-build -A check-hydra -o check-hydra.sh && ./check-hydra.sh'
#    agents:
#      system: x86_64-linux

  - label: 'stack-cabal-sync'
    command: 'nix-shell scripts/buildkite/stack-cabal-sync.nix --run scripts/buildkite/stack-cabal-sync.sh'
    agents:
      system: x86_64-linux

# FIXME:
#  - label: 'dependencies-at-master'
#    command: 'ci/check-dependencies-merged-to-master.sh'
#    agents:
#      system: x86_64-linux
