steps:
  - label: 'stack rebuild'
    env:
      STACK_ROOT: "/build/cardano-node.stack"
    command:
      - "rm -rf /build/cardano-node"
      - "cp -R . /build/cardano-node"
      - "cd /build/cardano-node"
      - "nix-build scripts/buildkite -o stack-rebuild"
      - "./stack-rebuild"
    agents:
      system: x86_64-linux
