# global filter; messages must have at least this severity to pass:
minSeverity: Info

# global file rotation settings:
rotation:
  rpLogLimitBytes: 5000000
  rpKeepFilesNum:  3
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "logs/genesis.log"
    scFormat: ScJson

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "logs/genesis.log"

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    'cardano.#messagecounters.aggregation':
      subtrace: NoTrace
    'cardano.#messagecounters.ekgview':
      subtrace: NoTrace
    'cardano.#messagecounters.switchboard':
      subtrace: NoTrace
    'cardano.#messagecounters.katip':
      subtrace: NoTrace
    'cardano.#messagecounters.monitoring':
      subtrace: NoTrace
  mapBackends:
    cardano.node.metrics.ChainDB:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.peers.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId: 0
Protocol: RealPBFT
NumCoreNodes: 1
RequiresNetworkMagic: RequiresMagic
PBftSignatureThreshold: 0.7
TurnOnLogging: False
ViewMode: SimpleView
TurnOnLogMetrics: False

##### Network Time Parameters #####

ResponseTimeout: 30000000
PollDelay: 1800000000
Servers: [ "0.pool.ntp.org"
         , "2.pool.ntp.org"
         , "3.pool.ntp.org"
         ]

#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0
