# global filter; messages must have at least this severity to pass:
minSeverity: Debug

# global file rotation settings:
rotation:
  rpLogLimitBytes: 25000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

# these backends are initialized:
setupBackends:
  - KatipBK
  #- TraceForwarderBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK
  #- TraceForwarderBK

# file to forward traced objects
#logOutput: "logs/log-pipe-0"

# if wanted, the GUI is listening on this port:
#hasGUI: 12871

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12781

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: FileSK
    scName: "logs/generator.log"
    scFormat: ScJson
  - scKind: StdoutSK
    scName: stdout
    scFormat: ScText
    scRotation: null

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - FileSK
    - "logs/generator.log"
  - - StdoutSK
    - stdout

# more options which can be passed as key-value pairs:
options:
  cfokey:
    value: "Release-1.0.0"
  mapSubtrace:
    '#ekgview':
      contents:
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: .monoclock.basic.
      - - tag: Contains
          contents: 'cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.cpuNs.timed.
      - - tag: StartsWith
          contents: '#ekgview.#aggregation.cardano.epoch-validation.benchmark'
        - - tag: Contains
            contents: diff.RTS.gcNum.timed.
      subtrace: FilterTrace
    'cardano.epoch-validation.utxo-stats':
      # Change the `subtrace` value to `Neutral` in order to log
      # `UTxO`-related messages during epoch validation.
      subtrace: NoTrace
    'messagecounters.aggregation':
      subtrace: NoTrace
    'messagecounters.ekgview':
      subtrace: NoTrace
    '#messagecounters.switchboard':
      subtrace: NoTrace
    '#messagecounters.katip':
      subtrace: NoTrace
    '#messagecounters.monitoring':
      subtrace: NoTrace
  mapBackends:
    cardano.node.metrics.ChainDB:
      - EKGViewBK
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.metrics:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
    cardano.node.peers.BlockFetchDecision:
      - kind: UserDefinedBK
        name: LiveViewBackend
##########################################################
############### Cardano Node Configuration ###############
##########################################################


NodeId: 99
Protocol: RealPBFT
NumCoreNodes: 1
RequiresNetworkMagic: RequiresMagic
PBftSignatureThreshold: 0.7
TurnOnLogging: True
ViewMode: SimpleView
TurnOnLogMetrics: True



#####    Update Parameters    #####

ApplicationName: cardano-sl
ApplicationVersion: 1
LastKnownBlockVersion-Major: 0
LastKnownBlockVersion-Minor: 2
LastKnownBlockVersion-Alt: 0
