# global filter; messages must have at least this severity to pass:
minSeverity: Info

# these backends are initialized:
setupBackends:
  - EKGViewBK
  - KatipBK

# if not indicated otherwise, then messages are passed to these backends:
defaultBackends:
  - KatipBK

# if wanted, the EKG interface is listening on this port:
#hasEKG: 12789

# if wanted, the Prometheus interface is using this port:
#hasPrometheus:
#  - "localhost"
#  - 12799

# here we set up outputs of logging in 'katip':
setupScribes:
  - scKind: StdoutSK
    scFormat: ScText
    scName: stdout

# if not indicated otherwise, then log output is directed to this:
defaultScribes:
  - - StdoutSK
    - stdout

# more options which can be passed as key-value pairs:
options:
  mapBackends:
    'byron-proxy.db.block count':
      - EKGViewBK
